### ISSUE TITLE
Host Process Crashed

### ISSUE THREAD

**Issue by Sonderwoods** [mcneel/SimpleRhinoTests#3]
Hi Ehsan and Giulio,

Great initiative and a must have for every developer!

I cloned the rep and with no changes, just trying to run the preset 12 tests with "Run All".

I'm getting `The active test run was aborted. Reason: Test host process crashed` before any of the tests run.

Turns out that if you hit "Run all", it will start with the Net framework tests which will crash Rhino 8 (if in Core mode) which will also skip the .NET7.0 tests.

Solution is (obviously for some) to right click on the .NET7.0 tests and hit Run.

Might be a small notice to add to the readme to avoid other getting into the same trap.

**Comment by Sonderwoods** [comment]
This error keeps popping up for me again.

When I add the reference to MyRhinoPlugin it cannot run tests. The MyRhinoPlugin is just the VS Template plugin.
Runs fine with jo project reference:
https://github.com/Sonderwoods/SimpleRhinoTests/tree/MSTest_Runs_WithoutRhinoProj
![image](https://github.com/mcneel/SimpleRhinoTests/assets/19936679/94e3b75c-d280-46b1-ad5c-7db0d589659a)

Fails with project reference:
https://github.com/Sonderwoods/SimpleRhinoTests/tree/MSTest_RhinoProjectFail
![image](https://github.com/mcneel/SimpleRhinoTests/assets/19936679/b6a8f298-3fce-4753-b685-2180552a37f7)


FWIW, Same issue happened for me in XUnit, NUnit and MSTest...

**Comment by Sonderwoods** [comment]
@fraguada any chance to have a look at the projects above and do you encounter same issue?

I was hoping we could touch some of this at the Mcneel Developer Meeting in Copenhagen.

**Comment by Sonderwoods** [comment]
changed sdk version didnt work. (had 7 and 8 installed).

`dotnet --info` revealed that I had multiple SDK versions installed:
```
.NET SDKs installed:
  7.0.317 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]
```

so in my solution directory i created `globals.json` with below content:
```
{
  "sdk": {
    "version": "7.0.317"
  }
}
```

now dotnet test will use net7 but this did not resolve it.

**Comment by Sonderwoods** [comment]
I found out that it's my rhino instance crashing (as the message said).

It works if i only have 1 test class but fails if i have several.

**Comment by Sonderwoods** [comment]
My issue was that my tests were dependent on projects that create *.rhp and *.gha files.
Changing the target extension of these to dll in their csprojs and adding a postbuild of copying the dll->.gha etc solved the issue.

Might want to add this to documentation/example

**Comment by eirannejad** [comment]
@Sonderwoods Closing this ticket as I don't see any issues with the example repo
